### ISSUE TITLE
Quick align issue

### ISSUE THREAD

**Issue by Shokoladina** [maxivz/interactivetoolsblender#19]
Python: Traceback (most recent call last):
  File "C:\Users\MOI\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\interactivetoolsblender-master\op\quick_align.py", line 167, in invoke
    self.target = self.mouse_raycast(context, event)
  File "C:\Users\MOI\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\interactivetoolsblender-master\op\quick_align.py", line 90, in mouse_raycast
    result, location, normal, index, object, matrix = context.scene.ray_cast(context.view_layer,
TypeError: Scene.ray_cast(): error with argument 1, "depsgraph" -  Function.depsgraph expected a Depsgraph type, not ViewLayer

**Comment by maxivz** [comment]
Fixed in bug fix branch, to be included in next release.
